version: '3'
services:
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: bala1
      POSTGRES_PASSWORD: bala123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  web:
    build: .
    container_name: django_web
    command: gunicorn interapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DB_NAME=bala
      - DJANGO_DB_USER=bala1
      - DJANGO_DB_PASSWORD=bala123
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:

